services:
  go:
    build:
      context: ./go-app/build
      dockerfile: Dockerfile
    container_name: tea_go
    depends_on:
      - db
    volumes:
      - ./go-app/:/go/src/app
    tty: true
    ports:
      - 8000:8000
  react:
    build:
      context: ./react-app/build
      dockerfile: Dockerfile
    container_name: tea_react
    tty: true
    volumes:
      - ./react-app/:/app/react
    # command: sh -c "cd /app/react && yarn install && yarn start"
    ports:
      - 5173:5173
  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
    container_name: tea_db
    environment:
      - MYSQL_DATABASE=tea_ceremony_inscription
      - MYSQL_ROOT_PASSWORD="mysql"
    ports:
      - 3306:3306

volumes:
  db-store: