services:
  go:
    build:
      context: ./go-app/build
      dockerfile: Dockerfile
    container_name: tea_go
    depends_on:
      - db
    volumes:
      - ./go-app/:/go/src/app
    tty: true
    ports:
      - 8000:8000
    networks:
      - app-net
    env_file: ./.env.local
  react:
    build:
      context: ./react-app/build
      dockerfile: Dockerfile
    container_name: tea_react
    tty: true
    volumes:
      - ./react-app/:/app/react
    # command: sh -c "cd /app/react && yarn install && yarn start"
    ports:
      - 5173:5173
    networks:
      - app-net
  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
    container_name: tea_db
    ports:
      - 3306:3306
    networks:
      - app-net
    env_file: ./.env.local

volumes:
  db-store:

networks:
  app-net:
    driver: bridge